# Form implementation generated from reading ui file 'f:\VS Code Workspace\[Project_Path]\Python_Path\Local\ReaWwise_Tool\WindowShow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import ctypes

myappid = "wo de app"
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)

class Ui_ReaWwise_Tool(object):
    def setupUi(self, ReaWwise_Tool):
        ReaWwise_Tool.setObjectName("ReaWwise_Tool")
        ReaWwise_Tool.resize(610, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\VS Code Workspace\\[Project_Path]\\Python_Path\\Local\\ReaWwise_Tool\\toolbar_video.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ReaWwise_Tool.setWindowIcon(icon)
        self.listView = QtWidgets.QListView(parent=ReaWwise_Tool)
        self.listView.setGeometry(QtCore.QRect(30, 110, 460, 190))
        self.listView.setObjectName("listView")
        self.RecordingStart = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.RecordingStart.setGeometry(QtCore.QRect(510, 200, 75, 31))
        self.RecordingStart.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.RecordingStart.setObjectName("RecordingStart")
        self.RecordingStop = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.RecordingStop.setGeometry(QtCore.QRect(510, 265, 75, 31))
        self.RecordingStop.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.RecordingStop.setObjectName("RecordingStop")
        self.Start = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.Start.setGeometry(QtCore.QRect(514, 50, 70, 45))
        self.Start.setStyleSheet("font: 700 11pt \"Microsoft YaHei UI\";\n"
"")
        self.Start.setObjectName("Start")
        self.PreviouMarker = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.PreviouMarker.setGeometry(QtCore.QRect(350, 20, 101, 31))
        self.PreviouMarker.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SizeVerCursor))
        self.PreviouMarker.setObjectName("PreviouMarker")
        self.InputLog = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.InputLog.setEnabled(True)
        self.InputLog.setGeometry(QtCore.QRect(145, 60, 121, 31))
        self.InputLog.setObjectName("InputLog")
        self.InsertMedia = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.InsertMedia.setGeometry(QtCore.QRect(145, 20, 81, 31))
        self.InsertMedia.setObjectName("InsertMedia")
        self.Stop = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.Stop.setGeometry(QtCore.QRect(514, 110, 70, 45))
        self.Stop.setStyleSheet("font: 700 11pt \"Microsoft YaHei UI\";")
        self.Stop.setObjectName("Stop")
        self.WwhispeAssistant = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.WwhispeAssistant.setGeometry(QtCore.QRect(40, 20, 75, 51))
        self.WwhispeAssistant.setObjectName("WwhispeAssistant")
        self.NextMarker = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.NextMarker.setGeometry(QtCore.QRect(350, 60, 101, 31))
        self.NextMarker.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SizeVerCursor))
        self.NextMarker.setObjectName("NextMarker")
        self.LinkCapture = QtWidgets.QCheckBox(parent=ReaWwise_Tool)
        self.LinkCapture.setGeometry(QtCore.QRect(515, 15, 70, 30))
        self.LinkCapture.setObjectName("LinkCapture")
        self.Clear = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.Clear.setGeometry(QtCore.QRect(30, 310, 75, 30))
        self.Clear.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.Clear.setObjectName("Clear")
        self.SaveLog = QtWidgets.QPushButton(parent=ReaWwise_Tool)
        self.SaveLog.setEnabled(True)
        self.SaveLog.setGeometry(QtCore.QRect(510, 310, 75, 30))
        self.SaveLog.setObjectName("SaveLog")
        self.groupBox = QtWidgets.QGroupBox(parent=ReaWwise_Tool)
        self.groupBox.setGeometry(QtCore.QRect(30, 9, 250, 90))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox.raise_()
        self.listView.raise_()
        self.RecordingStart.raise_()
        self.RecordingStop.raise_()
        self.Start.raise_()
        self.PreviouMarker.raise_()
        self.InputLog.raise_()
        self.InsertMedia.raise_()
        self.Stop.raise_()
        self.WwhispeAssistant.raise_()
        self.NextMarker.raise_()
        self.LinkCapture.raise_()
        self.Clear.raise_()
        self.SaveLog.raise_()

        # 设置列表视图不可编辑
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)

        self.retranslateUi(ReaWwise_Tool)
        QtCore.QMetaObject.connectSlotsByName(ReaWwise_Tool)

    def retranslateUi(self, ReaWwise_Tool):
        _translate = QtCore.QCoreApplication.translate
        ReaWwise_Tool.setWindowTitle(_translate("ReaWwise_Tool", "ReaWwise_Tool"))
        self.RecordingStart.setText(_translate("ReaWwise_Tool", "录制"))
        self.RecordingStop.setText(_translate("ReaWwise_Tool", "结束"))
        self.Start.setText(_translate("ReaWwise_Tool", "播放"))
        self.PreviouMarker.setText(_translate("ReaWwise_Tool", "转到上一个标记"))
        self.InputLog.setText(_translate("ReaWwise_Tool", "2. CaptureLog.txt"))
        self.InsertMedia.setText(_translate("ReaWwise_Tool", "1. 导入视频"))
        self.Stop.setText(_translate("ReaWwise_Tool", "停止"))
        self.WwhispeAssistant.setText(_translate("ReaWwise_Tool", "Wwhisper \n"
"Assistant"))
        self.NextMarker.setText(_translate("ReaWwise_Tool", "转到下一个标记"))
        self.LinkCapture.setText(_translate("ReaWwise_Tool", "Capture"))
        self.Clear.setText(_translate("ReaWwise_Tool", "清空"))
        self.SaveLog.setText(_translate("ReaWwise_Tool", "SaveLog"))
